### ISSUE TITLE
Can you explain more?

### ISSUE THREAD

**Issue by typo3ua** [extrameile/em_form_repeatablesave#1]
Hello!

Sorry! I do not fully understand, what makes this extension and for what it?

Can you explain more about your extension?

Thanks!

**Comment by opi99** [comment]
It is a finisher to save data of forms with have elements which repeat themself, for example multiple address blocks inside the form. Such elements could be created like https://www.tritum.de/typo3-cms/typo3-extensions/typo3-form-framework/repeatable-form-element-teil-1/ (in german only).

**Comment by typo3ua** [comment]
so far as I understood, if I will be using this "ext:repeatable_form_elements" with your "ext:em_form_repeatablesave" then I can save in a database more one record... for example records as "images", "categories", "tags"... I correct to understand it?

**Comment by opi99** [comment]
Yes, this is then possible while using ext:form.

**Comment by typo3ua** [comment]
Thank you so much!
